# Site settings
title: Théo Zimmermann
description: "Mostly a place to share ideas and thoughts."
#Description will appear in your document head meta (for Google search results) and in your feed.xml site description.
baseurl: ""
url: "http://www.theozimmermann.net"
timezone: "Europe/Paris"
#author:
#  name: Théo Zimmermann
email: "theo.zimmermann [...] ens.fr"
linkedin_username: theozim
twitter_username: Zimm_i48
github_username: Zimmi48

# Build settings
markdown: kramdown
permalink: pretty
