# Site settings
title: Théo Zimmermann
#Description will appear in your document head meta (for Google search results) and in your feed.xml site description.

url: "https://www.theozimmermann.net"
timezone: "Europe/Paris"
email: "theo.zimmermann [...] univ-paris-diderot.fr"
publickey: "/zimmermann.asc"
linkedin_username: theozim
twitter_username: Zimm_i48
github_username: Zimmi48

# Build settings
markdown: kramdown
permalink: /:year/:month/:title/

# Multilingual settings (origin: http://sylvaindurand.org/rendre-jekyll-multilingue/)
t:
  en:
    baseurl: "/en"
    description: "Mostly a place to share ideas and thoughts."
    translation: "lire en français"
    short: "Short URL:"
    contact: "E-mail:"
    gpg: "My GPG key"
    copyright-texts: "All texts by Théo Zimmermann appearing for the first time on this page are licensed under"
    copyright-documents: "This does not apply to any document (in particular PDF document) linked from this page."
    copyright-code: "All code snippets by Théo Zimmermann appearing for the first time on this page are dedicated to the public domain following the terms of"
    copyright-images: "All images appearing on this website are fully copyrighted and remain the sole property of their respective authors. You may not use them unless stated otherwise."
    subscribe-title: "Subscribe by e-mail or"
    subscribe-email: "E-mail address"
    subscribe-lang: "Language settings"
    subscribe-button: "Subscribe"
    profil-credits: "Profile by Jules Zimmermann"
  fr:
    baseurl: "/fr"
    description: "Là où je partage quelques-unes de mes idées."
    translation: "read in English"
    short: "Lien abrégé :"
    contact: "E-mail :"
    gpg: "Ma clé GPG"
    copyright-texts: "Tous les écrits de Théo Zimmermann qui sont présentés pour la première fois sur cette page sont mis à disposition selon les termes de la licence"
    copyright-documents: "Ceci ne concerne pas les documents (en particulier tout document PDF) accessibles par un lien depuis cette page."
    copyright-code: "Tous les extraits de code dont l'auteur est Théo Zimmermann et qui sont présentés pour la première fois sur cette page sont dédiés au domaine public, suivant les termes de"
    copyright-images: "Toute image apparaissant sur ce site reste pleinement protégée par le droit d'auteur et son auteur en conserve la propriété exclusive. Vous n'avez pas le droit de l'utiliser à moins cela ne soit explicitement précisé."
    subscribe-title: "Abonnez-vous par e-mail ou"
    subscribe-email: "Adresse e-mail"
    subscribe-lang: "Paramètres linguistiques"
    subscribe-button: "S'abonner"
    profil-credits: "Portrait par Jules Zimmermann"

# Redirects function for short URLs
plugins:
  - jekyll-redirect-from
