# Site settings
title: Théo Zimmermann
description: "Mostly a place to share ideas and thoughts."
#Description will appear in your document head meta (for Google search results) and in your feed.xml site description.

url: "http://www.theozimmermann.net"
timezone: "Europe/Paris"
email: "theo.zimmermann [...] ens.fr"
linkedin_username: theozim
twitter_username: Zimm_i48
github_username: Zimmi48

# Build settings
markdown: kramdown
permalink: pretty

# Multilingual settings (origin: http://sylvain.durand.tf/site-multilingue-avec-jekyll/)
t:
  fr:
    translation: "read in English"
  en:
    translation: "lire en français"
baseurl: ""
baseurl-fr: "/accueil"

# Redirects function for short URLs
gems:
  - jekyll-redirect-from