# Site settings
title: Théo Zimmermann
#Description will appear in your document head meta (for Google search results) and in your feed.xml site description.

url: "http://www.theozimmermann.net"
timezone: "Europe/Paris"
email: "theo.zimmermann [...] ens.fr"
linkedin_username: theozim
twitter_username: Zimm_i48
github_username: Zimmi48

# Build settings
markdown: kramdown
permalink: pretty

# Multilingual settings (origin: http://sylvain.durand.tf/site-multilingue-avec-jekyll/)
t:
  en:
    baseurl: ""
    description: "Mostly a place to share ideas and thoughts."
    translation: "lire en français"
    short: "Short URL:"
  fr:
    baseurl: "/accueil"
    description: "Un endroit où partager des idées."
    translation: "read in English"
    short: "Lien abrégé :"

# Redirects function for short URLs
gems:
  - jekyll-redirect-from